#if !defined(_DEFAULT_SOURCE)
#define _DEFAULT_SOURCE 1
#endif
/*
** RistrettoDB Embedded
**
** This file contains the complete implementation of RistrettoDB in a single
** source file. Simply compile this file along with your application.
**
** To use embedded (Option 1 - Self-contained):
**   1. Include this ristretto.c file in your project
**   2. Define RISTRETTO_EMBEDDED before including
**   3. Example:
**      #define RISTRETTO_EMBEDDED
**      #include "ristretto.c"  // Note: .c not .h
**
** To use with separate header (Option 2):
**   1. Include ristretto.h in your source files
**   2. Compile ristretto.c separately
**   3. Link together
**
** Generated by embed.py
** RistrettoDB Version: 0.3.0
** Homepage: https://github.com/MonkeyIsNull/RistrettoDB
*/

#ifndef RISTRETTO_EMBEDDED

/* When used as a separate compilation unit, include the public header */
#include "ristretto.h"

#else

/* 
** When used as an embedded, provide all definitions inline
** This section replaces ristretto.h when RISTRETTO_EMBEDDED is defined
*/

#ifndef RISTRETTO_H
#define RISTRETTO_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <assert.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
** RistrettoDB Version Information
*/
#define RISTRETTO_VERSION        "0.3.0"
#define RISTRETTO_VERSION_NUMBER 3000
#define RISTRETTO_VERSION_MAJOR  0
#define RISTRETTO_VERSION_MINOR  3
#define RISTRETTO_VERSION_PATCH  0

const char* ristretto_version(void);
int ristretto_version_number(void);

/*
** Table V2 API Constants (must match the internal table_v2.h values)
*/
#define RISTRETTO_MAX_COLUMNS 14
#define RISTRETTO_MAX_COLUMN_NAME 32
#define RISTRETTO_TABLE_HEADER_SIZE 1024
#define RISTRETTO_INITIAL_FILE_SIZE (1024 * 1024)
#define RISTRETTO_GROWTH_FACTOR 2
#define RISTRETTO_SYNC_INTERVAL_ROWS 512
#define RISTRETTO_SYNC_INTERVAL_MS 100
#define RISTRETTO_TABLE_MAGIC "RSTRDB\x00\x00"
#define RISTRETTO_TABLE_VERSION 3

typedef enum {
    RISTRETTO_COL_INTEGER = 1,
    RISTRETTO_COL_REAL = 2,
    RISTRETTO_COL_TEXT = 3,
    RISTRETTO_COL_NULLABLE = 4
} RistrettoColumnType;

typedef enum {
    RISTRETTO_CREATE_NEW = 0,
    RISTRETTO_CREATE_OR_TRUNCATE = 1,
    RISTRETTO_OPEN_OR_CREATE = 2
} RistrettoOpenMode;

typedef struct RistrettoTable RistrettoTable;

typedef struct {
    RistrettoColumnType type;
    union {
        int64_t integer;
        double real;
        struct {
            char *data;
            size_t length;
        } text;
    } value;
    bool is_null;
} RistrettoValue;

typedef struct {
    char name[RISTRETTO_MAX_COLUMN_NAME];
    uint8_t type;
    uint8_t length;
    uint16_t offset;
    uint8_t reserved[4];
} RistrettoColumnDesc;

typedef struct {
    char magic[8];
    uint32_t version;
    uint32_t row_size;
    uint64_t num_rows;
    uint32_t column_count;
    uint8_t reserved[12];
    RistrettoColumnDesc columns[RISTRETTO_MAX_COLUMNS];
} RistrettoTableHeader;

_Static_assert(RISTRETTO_TABLE_HEADER_SIZE >= sizeof(RistrettoTableHeader),
               "row data must not overlap the table header");

/*
** Table V2 API Functions
*/
RistrettoTable* ristretto_table_create(const char *name, const char *schema_sql);
RistrettoTable* ristretto_table_open(const char *name);
RistrettoTable* ristretto_table_create_ex(const char *name, const char *schema_sql,
                                          const char *base_dir, int open_mode);
RistrettoTable* ristretto_table_open_ex(const char *name, const char *base_dir);
void ristretto_table_close(RistrettoTable *table);

bool ristretto_table_append_row(RistrettoTable *table, const RistrettoValue *values);
bool ristretto_table_append_row_n(RistrettoTable *table, const RistrettoValue *values,
                                  uint32_t value_count);
bool ristretto_table_select(RistrettoTable *table,
                           void (*callback)(void *ctx, const RistrettoValue *row), void *ctx);

bool ristretto_table_flush(RistrettoTable *table);
bool ristretto_table_flush_durable(RistrettoTable *table);
bool ristretto_table_remap(RistrettoTable *table);
bool ristretto_table_ensure_space(RistrettoTable *table, size_t needed_bytes);

bool ristretto_table_parse_schema(const char *schema_sql, RistrettoColumnDesc *columns,
                                 uint32_t *column_count, uint32_t *row_size);
const RistrettoColumnDesc* ristretto_table_get_column(RistrettoTable *table, const char *name);
size_t ristretto_table_get_row_count(RistrettoTable *table);

RistrettoValue ristretto_value_integer(int64_t val);
RistrettoValue ristretto_value_real(double val);
RistrettoValue ristretto_value_text(const char *str);
RistrettoValue ristretto_value_null(void);
void ristretto_value_destroy(RistrettoValue *value);

bool ristretto_table_pack_row(RistrettoTable *table, const RistrettoValue *values, uint8_t *row_buffer);
bool ristretto_table_unpack_row(RistrettoTable *table, const uint8_t *row_buffer, RistrettoValue *values);

uint64_t ristretto_get_time_ms(void);
bool ristretto_create_data_directory(void);

/*
** NOTE: The amalgamation deliberately omits the user-facing compatibility
** macros (#define table_create ristretto_table_create, #define Value
** RistrettoValue, ...). In a single translation unit they would rewrite the
** inlined internal engine bodies (which define Value / table_create / ...) and
** collide. Embedding code should call the ristretto_*-prefixed API directly.
*/

#ifdef __cplusplus
}
#endif

#endif /* RISTRETTO_H */

#endif /* !RISTRETTO_EMBEDDED */

/* Standard library includes */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <assert.h>
#include <ctype.h>
#include <time.h>
#include <sys/mman.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>


/* BEGIN src/version.c */
/*
** RistrettoDB Version Information
**
** This file contains version information and compilation details
** for the RistrettoDB library.
*/


/*
** Return the version string
*/
const char* ristretto_version(void) {
    return RISTRETTO_VERSION;
}

/*
** Return the version number
*/
int ristretto_version_number(void) {
    return RISTRETTO_VERSION_NUMBER;
}

/* END src/version.c */

/* BEGIN src/table_v2.c */
/* BEGIN table_v2.h */
#ifndef RISTRETTO_TABLE_V2_H
#define RISTRETTO_TABLE_V2_H


#define MAX_COLUMNS 14
#define MAX_COLUMN_NAME 32
// Every row begins with a fixed-width NULL bitmap: bit i is set when column i
// is NULL. Derive every row offset/region from this macro (never a hardcoded
// width) so a future MAX_COLUMNS bump stays correct.
#define NULL_BITMAP_BYTES ((MAX_COLUMNS + 7) / 8)
_Static_assert(MAX_COLUMNS <= NULL_BITMAP_BYTES * 8, "null bitmap too small");
// Header region reserved at the start of every .rdb file. Must be >= the
// actual sizeof(TableHeader) (checked by the _Static_assert below) so that
// row data written at TABLE_HEADER_SIZE never overlaps the column-descriptor
// array. 1024 leaves generous headroom and is page-friendly.
#define TABLE_HEADER_SIZE 1024
#define INITIAL_FILE_SIZE (1024 * 1024)  // 1 MB initial size
#define GROWTH_FACTOR 2                   // Double size when growing
#define SYNC_INTERVAL_ROWS 512           // Sync every N rows
#define SYNC_INTERVAL_MS 100             // Sync every N milliseconds

// Magic bytes for file format identification
#define TABLE_MAGIC "RSTRDB\x00\x00"
// Format version. Bumped 1 -> 2 when TABLE_HEADER_SIZE grew from 256 to 1024.
// Bumped 2 -> 3 for the per-row NULL bitmap (NULLs now persist and round-trip):
// the row layout changed, so v1/v2 files are cleanly rejected on open.
#define TABLE_VERSION 3

// Open modes for table_create_ex / table_open_ex.
typedef enum {
    RDB_CREATE_NEW = 0,          // Create; fail (O_EXCL) if the file exists
    RDB_CREATE_OR_TRUNCATE = 1,  // Create or truncate existing (legacy default)
    RDB_OPEN_OR_CREATE = 2       // Open existing, or create if absent
} RdbOpenMode;

typedef enum {
    COL_TYPE_INTEGER = 1,
    COL_TYPE_REAL = 2,
    COL_TYPE_TEXT = 3,
    COL_TYPE_NULLABLE = 4
} ColumnType;

typedef struct {
    char name[MAX_COLUMN_NAME];  // Column name (truncated/padded)
    uint8_t type;                // ColumnType
    uint8_t length;              // Bytes if TEXT, 0 for INTEGER/REAL
    uint16_t offset;             // Byte offset within row
    uint8_t reserved[4];         // Padding/reserved for future use
} ColumnDesc;

typedef struct {
    char magic[8];               // "RSTRDB\x00\x00"
    uint32_t version;            // File format version
    uint32_t row_size;           // Size in bytes of a single row
    uint64_t num_rows;           // Number of rows written
    uint32_t column_count;       // Number of columns
    uint8_t reserved[12];        // Reserved for future use
    ColumnDesc columns[MAX_COLUMNS];  // Column descriptors
} TableHeader;

// Row data must never overlap the header region. If this fails, raise
// TABLE_HEADER_SIZE (and bump TABLE_VERSION since the on-disk layout changes).
_Static_assert(TABLE_HEADER_SIZE >= sizeof(TableHeader),
               "row data must not overlap the table header");

typedef struct {
    char name[64];               // Table name
    int fd;                      // File descriptor
    uint8_t *mapped_ptr;         // Memory-mapped file pointer
    size_t mapped_size;          // Current mapped size
    size_t write_offset;         // Current write position
    TableHeader *header;         // Pointer to header in mapped memory
    
    // Performance tracking
    uint64_t rows_since_sync;    // Rows written since last sync
    uint64_t last_sync_time_ms;  // Last sync timestamp
    
    // File path for remapping
    char file_path[256];
} Table;

typedef struct {
    ColumnType type;
    union {
        int64_t integer;
        double real;
        struct {
            char *data;
            size_t length;
        } text;
    } value;
    bool is_null;
} Value;

// Table lifecycle functions
Table* table_create(const char *name, const char *schema_sql);
Table* table_open(const char *name);
void table_close(Table *table);

// Extended lifecycle: choose the storage directory (base_dir, NULL = "data")
// and, for create, the open mode (RDB_CREATE_NEW / _OR_TRUNCATE / OPEN_OR_CREATE).
// The two-argument table_create/table_open above are thin wrappers over these
// with base_dir="data" and open_mode=RDB_CREATE_OR_TRUNCATE.
Table* table_create_ex(const char *name, const char *schema_sql,
                       const char *base_dir, int open_mode);
Table* table_open_ex(const char *name, const char *base_dir);

// Core operations
// table_append_row trusts that values[] holds exactly header->column_count
// entries. table_append_row_n validates the count first (recommended for
// language bindings and untrusted callers).
bool table_append_row(Table *table, const Value *values);
bool table_append_row_n(Table *table, const Value *values, uint32_t value_count);
// Scans every row and invokes callback once per row. V2 has no WHERE clause:
// scan and filter in your application.
bool table_select(Table *table,
                 void (*callback)(void *ctx, const Value *row), void *ctx);

// File management
bool table_flush(Table *table);         // MS_ASYNC (fast, not durable)
bool table_flush_durable(Table *table); // MS_SYNC + fsync (durable)
bool table_remap(Table *table);
bool table_ensure_space(Table *table, size_t needed_bytes);

// Schema and metadata
bool table_parse_schema(const char *schema_sql, ColumnDesc *columns, 
                       uint32_t *column_count, uint32_t *row_size);
const ColumnDesc* table_get_column(Table *table, const char *name);
size_t table_get_row_count(Table *table);

// Value utilities
Value value_integer(int64_t val);
Value value_real(double val);
Value value_text(const char *str);
Value value_null(void);
void value_destroy(Value *value);

// Row packing/unpacking
bool table_pack_row(Table *table, const Value *values, uint8_t *row_buffer);
bool table_unpack_row(Table *table, const uint8_t *row_buffer, Value *values);

// Utility functions
uint64_t get_time_ms(void);
bool create_data_directory(void);               // creates "data" in the CWD
bool create_data_directory_in(const char *base_dir); // creates base_dir (NULL = "data")

#endif

/* END table_v2.h */

// Utility functions
uint64_t get_time_ms(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}

bool create_data_directory_in(const char *base_dir) {
    if (!base_dir) base_dir = "data";
    struct stat st = {0};
    if (stat(base_dir, &st) == -1) {
        if (mkdir(base_dir, 0755) == 0) return true;
        // Tolerate a concurrent creator.
        return errno == EEXIST;
    }
    return true;
}

bool create_data_directory(void) {
    return create_data_directory_in("data");
}

// Value constructors
Value value_integer(int64_t val) {
    Value v = {0};
    v.type = COL_TYPE_INTEGER;
    v.value.integer = val;
    v.is_null = false;
    return v;
}

Value value_real(double val) {
    Value v = {0};
    v.type = COL_TYPE_REAL;
    v.value.real = val;
    v.is_null = false;
    return v;
}

Value value_text(const char *str) {
    Value v = {0};
    v.type = COL_TYPE_TEXT;
    if (str) {
        size_t len = strlen(str);
        v.value.text.data = malloc(len + 1);
        if (v.value.text.data) {
            strcpy(v.value.text.data, str);
            v.value.text.length = len;
        }
    }
    v.is_null = (str == NULL);
    return v;
}

Value value_null(void) {
    Value v = {0};
    v.is_null = true;
    return v;
}

void value_destroy(Value *value) {
    if (value && value->type == COL_TYPE_TEXT && value->value.text.data) {
        free(value->value.text.data);
        value->value.text.data = NULL;
        value->value.text.length = 0;
    }
}

// Schema parsing (simplified - will need full parser integration later)
bool table_parse_schema(const char *schema_sql, ColumnDesc *columns, 
                       uint32_t *column_count, uint32_t *row_size) {
    // Simple parser for basic CREATE TABLE statements
    // Format: CREATE TABLE name (col1 TYPE, col2 TYPE(size), ...)
    
    *column_count = 0;
    *row_size = 0;
    
    // Find the opening parenthesis
    const char *start = strchr(schema_sql, '(');
    if (!start) return false;
    start++;
    
    const char *end = strrchr(schema_sql, ')');
    if (!end) return false;
    
    // Parse column definitions. Every row starts with a NULL_BITMAP_BYTES-wide
    // NULL bitmap, so column data begins after it.
    char col_def[256];
    const char *current = start;
    uint32_t offset = NULL_BITMAP_BYTES;

    while (current < end && *column_count < MAX_COLUMNS) {
        // Extract column definition
        const char *comma = strchr(current, ',');
        if (!comma) comma = end;
        
        size_t def_len = comma - current;
        if (def_len >= sizeof(col_def)) def_len = sizeof(col_def) - 1;
        
        strncpy(col_def, current, def_len);
        col_def[def_len] = '\0';
        
        // Parse column name and type
        char name[MAX_COLUMN_NAME] = {0};
        char type_str[32] = {0};
        int length = 0;
        
        if (sscanf(col_def, " %31s %31s", name, type_str) < 2) {
            break;
        }
        
        // Determine column type and size
        ColumnDesc *col = &columns[*column_count];
        strncpy(col->name, name, MAX_COLUMN_NAME - 1);
        col->offset = offset;
        
        if (strncmp(type_str, "INTEGER", 7) == 0) {
            col->type = COL_TYPE_INTEGER;
            col->length = 8;
        } else if (strncmp(type_str, "REAL", 4) == 0) {
            col->type = COL_TYPE_REAL;
            col->length = 8;
        } else if (strncmp(type_str, "TEXT", 4) == 0) {
            col->type = COL_TYPE_TEXT;
            // Parse TEXT(n) format
            if (sscanf(type_str, "TEXT(%d)", &length) == 1) {
                col->length = (length > 255) ? 255 : length;
            } else {
                col->length = 64; // Default text size
            }
        } else {
            return false; // Unsupported type
        }
        
        offset += col->length;
        (*column_count)++;
        
        current = comma + 1;
        if (comma == end) break;
    }
    
    *row_size = offset;
    return *column_count > 0;
}

// Table creation (extended)
Table* table_create_ex(const char *name, const char *schema_sql,
                       const char *base_dir, int open_mode) {
    if (!name || !schema_sql) return NULL;
    if (!base_dir) base_dir = "data";

    if (!create_data_directory_in(base_dir)) {
        return NULL;
    }

    Table *table = calloc(1, sizeof(Table));
    if (!table) return NULL;

    // Parse schema into temporary variables
    ColumnDesc temp_columns[MAX_COLUMNS];
    uint32_t temp_column_count, temp_row_size;
    if (!table_parse_schema(schema_sql, temp_columns, &temp_column_count, &temp_row_size)) {
        free(table);
        return NULL;
    }

    // Create file path
    snprintf(table->file_path, sizeof(table->file_path), "%s/%s.rdb", base_dir, name);
    strncpy(table->name, name, sizeof(table->name) - 1);

    // RDB_OPEN_OR_CREATE: resume an existing table rather than recreating it.
    if (open_mode == RDB_OPEN_OR_CREATE) {
        struct stat existing;
        if (stat(table->file_path, &existing) == 0 &&
            existing.st_size >= (off_t)TABLE_HEADER_SIZE) {
            free(table);
            return table_open_ex(name, base_dir);
        }
    }

    // Select open flags based on the requested mode.
    int flags = O_CREAT | O_RDWR;
    switch (open_mode) {
        case RDB_CREATE_NEW:         flags |= O_EXCL;  break; // fail if exists
        case RDB_OPEN_OR_CREATE:     /* no O_TRUNC, no O_EXCL */ break;
        case RDB_CREATE_OR_TRUNCATE:
        default:                     flags |= O_TRUNC; break;
    }

    // Create and open file
    table->fd = open(table->file_path, flags, 0644);
    if (table->fd == -1) {
        if (open_mode == RDB_CREATE_NEW && errno == EEXIST) {
            fprintf(stderr, "table_create: '%s' already exists (RDB_CREATE_NEW)\n",
                    table->file_path);
        }
        free(table);
        return NULL;
    }

    // Advisory single-writer lock. NB: advisory only, and a no-op on some
    // network filesystems (NFS/SMB); released implicitly on close(fd).
    if (flock(table->fd, LOCK_EX | LOCK_NB) == -1) {
        if (errno == EWOULDBLOCK) {
            fprintf(stderr, "table_create: '%s' locked by another process\n",
                    table->file_path);
        }
        close(table->fd);
        free(table);
        return NULL;
    }

    // Set initial file size
    if (ftruncate(table->fd, INITIAL_FILE_SIZE) == -1) {
        close(table->fd);
        free(table);
        return NULL;
    }
    
    // Memory map the file
    table->mapped_ptr = mmap(NULL, INITIAL_FILE_SIZE, PROT_READ | PROT_WRITE, 
                            MAP_SHARED, table->fd, 0);
    if (table->mapped_ptr == MAP_FAILED) {
        close(table->fd);
        free(table);
        return NULL;
    }
    
    table->mapped_size = INITIAL_FILE_SIZE;
    table->header = (TableHeader*)table->mapped_ptr;
    table->write_offset = TABLE_HEADER_SIZE;
    
    // Initialize header
    memcpy(table->header->magic, TABLE_MAGIC, 8);
    table->header->version = TABLE_VERSION;
    table->header->num_rows = 0;
    
    // Copy parsed schema to header
    table->header->column_count = temp_column_count;
    table->header->row_size = temp_row_size;
    memcpy(table->header->columns, temp_columns, sizeof(ColumnDesc) * temp_column_count);
    
    table->rows_since_sync = 0;
    table->last_sync_time_ms = get_time_ms();

    return table;
}

// Table creation. Convenience wrapper: stores under "data/" and TRUNCATES any
// existing file. For non-destructive creation use table_create_ex with
// RDB_CREATE_NEW, and pass a base_dir to control the storage location.
Table* table_create(const char *name, const char *schema_sql) {
    return table_create_ex(name, schema_sql, "data", RDB_CREATE_OR_TRUNCATE);
}

// Table opening (extended)
Table* table_open_ex(const char *name, const char *base_dir) {
    if (!name) return NULL;
    if (!base_dir) base_dir = "data";

    Table *table = calloc(1, sizeof(Table));
    if (!table) return NULL;

    // Create file path
    snprintf(table->file_path, sizeof(table->file_path), "%s/%s.rdb", base_dir, name);
    strncpy(table->name, name, sizeof(table->name) - 1);

    // Open existing file
    table->fd = open(table->file_path, O_RDWR);
    if (table->fd == -1) {
        free(table);
        return NULL;
    }

    // Advisory single-writer lock (see table_create_ex).
    if (flock(table->fd, LOCK_EX | LOCK_NB) == -1) {
        if (errno == EWOULDBLOCK) {
            fprintf(stderr, "table_open: '%s' locked by another process\n",
                    table->file_path);
        }
        close(table->fd);
        free(table);
        return NULL;
    }

    // Get file size
    struct stat st;
    if (fstat(table->fd, &st) == -1) {
        close(table->fd);
        free(table);
        return NULL;
    }
    
    if (st.st_size < TABLE_HEADER_SIZE) {
        close(table->fd);
        free(table);
        return NULL;
    }
    
    // Memory map the file
    table->mapped_ptr = mmap(NULL, st.st_size, PROT_READ | PROT_WRITE, 
                            MAP_SHARED, table->fd, 0);
    if (table->mapped_ptr == MAP_FAILED) {
        close(table->fd);
        free(table);
        return NULL;
    }
    
    table->mapped_size = st.st_size;
    table->header = (TableHeader*)table->mapped_ptr;
    
    // Validate header
    if (memcmp(table->header->magic, TABLE_MAGIC, 8) != 0 ||
        table->header->version != TABLE_VERSION) {
        munmap(table->mapped_ptr, table->mapped_size);
        close(table->fd);
        free(table);
        return NULL;
    }
    
    // Calculate write offset
    table->write_offset = TABLE_HEADER_SIZE + (table->header->num_rows * table->header->row_size);
    table->rows_since_sync = 0;
    table->last_sync_time_ms = get_time_ms();

    return table;
}

// Table opening. Convenience wrapper: resumes "data/<name>.rdb".
Table* table_open(const char *name) {
    return table_open_ex(name, "data");
}

// Table closing
void table_close(Table *table) {
    if (!table) return;

    // Durable flush at close so a reopen sees every committed row (covers the
    // header region, making num_rows durable). Runs once, before munmap.
    if (table->mapped_ptr && table->mapped_ptr != MAP_FAILED) {
        msync(table->mapped_ptr, table->write_offset, MS_SYNC);
    }
    if (table->fd != -1) {
        fsync(table->fd);
    }

    if (table->mapped_ptr && table->mapped_ptr != MAP_FAILED) {
        munmap(table->mapped_ptr, table->mapped_size);
    }

    if (table->fd != -1) {
        close(table->fd);  // also releases the advisory flock
    }

    free(table);
}

// File growth and remapping
bool table_ensure_space(Table *table, size_t needed_bytes) {
    if (table->write_offset + needed_bytes <= table->mapped_size) {
        return true; // Already have enough space
    }
    
    return table_remap(table);
}

bool table_remap(Table *table) {
    size_t new_size = table->mapped_size * GROWTH_FACTOR;
    
    // Unmap current mapping
    if (munmap(table->mapped_ptr, table->mapped_size) == -1) {
        return false;
    }
    
    // Resize file
    if (ftruncate(table->fd, new_size) == -1) {
        return false;
    }
    
    // Remap with new size
    table->mapped_ptr = mmap(NULL, new_size, PROT_READ | PROT_WRITE, 
                            MAP_SHARED, table->fd, 0);
    if (table->mapped_ptr == MAP_FAILED) {
        return false;
    }
    
    table->mapped_size = new_size;
    table->header = (TableHeader*)table->mapped_ptr;
    
    return true;
}

// Row packing
bool table_pack_row(Table *table, const Value *values, uint8_t *row_buffer) {
    // Zeroing the whole row also clears the leading NULL bitmap.
    memset(row_buffer, 0, table->header->row_size);

    for (uint32_t i = 0; i < table->header->column_count; i++) {
        const ColumnDesc *col = &table->header->columns[i];
        const Value *val = &values[i];
        uint8_t *dest = row_buffer + col->offset;

        if (val->is_null) {
            // Record NULL in the bitmap; leave the value bytes zeroed.
            row_buffer[i / 8] |= (uint8_t)(1u << (i % 8));
            continue;
        }

        switch (col->type) {
            case COL_TYPE_INTEGER:
                // memcpy (not a type-punned store): dest is not 8-byte aligned
                // once the NULL bitmap shifts columns, and a misaligned scalar
                // store is UB / SIGBUS on strict-alignment targets.
                memcpy(dest, &val->value.integer, sizeof(int64_t));
                break;

            case COL_TYPE_REAL:
                memcpy(dest, &val->value.real, sizeof(double));
                break;

            case COL_TYPE_TEXT:
                // Guard zero-width TEXT: col->length is uint8_t, so col->length-1
                // would wrap to a huge size_t and defeat the clamp below.
                if (col->length == 0) {
                    break;
                }
                if (val->value.text.data) {
                    size_t copy_len = val->value.text.length;
                    if (copy_len > (size_t)(col->length - 1)) {
                        copy_len = (size_t)(col->length - 1);
                    }
                    memcpy(dest, val->value.text.data, copy_len);
                    dest[copy_len] = '\0';
                }
                break;
                
            default:
                return false;
        }
    }
    
    return true;
}

// Row unpacking
bool table_unpack_row(Table *table, const uint8_t *row_buffer, Value *values) {
    for (uint32_t i = 0; i < table->header->column_count; i++) {
        const ColumnDesc *col = &table->header->columns[i];
        const uint8_t *src = row_buffer + col->offset;
        Value *val = &values[i];

        bool is_null = (row_buffer[i / 8] & (uint8_t)(1u << (i % 8))) != 0;
        if (is_null) {
            // Fully initialise the union (text.data = NULL, length = 0). The
            // caller frees each Value via value_destroy, which free()s
            // value.text.data; leaving it uninitialised would free garbage.
            *val = (Value){ .type = col->type, .is_null = true };
            continue;
        }

        val->type = col->type;
        val->is_null = false;

        switch (col->type) {
            case COL_TYPE_INTEGER:
                // memcpy: src may be unaligned (NULL bitmap shifts columns).
                memcpy(&val->value.integer, src, sizeof(int64_t));
                break;

            case COL_TYPE_REAL:
                memcpy(&val->value.real, src, sizeof(double));
                break;

            case COL_TYPE_TEXT:
                val->value.text.length = strnlen((char*)src, col->length);
                val->value.text.data = malloc(val->value.text.length + 1);
                if (val->value.text.data) {
                    memcpy(val->value.text.data, src, val->value.text.length);
                    val->value.text.data[val->value.text.length] = '\0';
                } else {
                    return false;
                }
                break;

            default:
                return false;
        }
    }

    return true;
}

// Ultra-fast row insertion. Trusts that values[] holds exactly
// header->column_count entries; use table_append_row_n to validate the count.
bool table_append_row(Table *table, const Value *values) {
    if (!table || !values || table->header->column_count == 0) return false;

    // Ensure we have space for the row
    if (!table_ensure_space(table, table->header->row_size)) {
        return false;
    }
    
    // Pack row directly into mapped memory
    uint8_t *row_dest = table->mapped_ptr + table->write_offset;
    if (!table_pack_row(table, values, row_dest)) {
        return false;
    }
    
    // Update write position and row count
    table->write_offset += table->header->row_size;
    table->header->num_rows++;
    table->rows_since_sync++;
    
    // Check if we should sync
    uint64_t current_time = get_time_ms();
    if (table->rows_since_sync >= SYNC_INTERVAL_ROWS ||
        (current_time - table->last_sync_time_ms) >= SYNC_INTERVAL_MS) {
        table_flush(table);
    }
    
    return true;
}

// Count-checked row insertion. Rejects a values[] array whose length does not
// match the column count (prevents out-of-bounds reads in table_pack_row).
bool table_append_row_n(Table *table, const Value *values, uint32_t value_count) {
    if (!table || !values) return false;
    if (value_count != table->header->column_count) {
        fprintf(stderr, "table_append_row_n: expected %u values, got %u\n",
                table->header->column_count, value_count);
        return false;
    }
    return table_append_row(table, values);
}

// Sync and durability (fast, asynchronous).
bool table_flush(Table *table) {
    if (!table || !table->mapped_ptr) return false;

    // Sync memory-mapped region
    if (msync(table->mapped_ptr, table->write_offset, MS_ASYNC) == -1) {
        return false;
    }

    table->rows_since_sync = 0;
    table->last_sync_time_ms = get_time_ms();

    return true;
}

// Durable flush: synchronous msync + fsync. Use when the caller needs the data
// on stable storage; table_close also flushes durably.
bool table_flush_durable(Table *table) {
    if (!table || !table->mapped_ptr) return false;

    if (msync(table->mapped_ptr, table->write_offset, MS_SYNC) == -1) {
        return false;
    }
    if (table->fd != -1 && fsync(table->fd) == -1) {
        return false;
    }

    table->rows_since_sync = 0;
    table->last_sync_time_ms = get_time_ms();
    return true;
}

// Table scanning. V2 has no WHERE clause; scan every row and let the caller
// filter in application code.
bool table_select(Table *table,
                 void (*callback)(void *ctx, const Value *row), void *ctx) {
    if (!table || !callback) return false;

    Value *row_values = malloc(sizeof(Value) * table->header->column_count);
    if (!row_values) return false;
    
    uint8_t *current_row = table->mapped_ptr + TABLE_HEADER_SIZE;
    
    for (uint64_t i = 0; i < table->header->num_rows; i++) {
        if (table_unpack_row(table, current_row, row_values)) {
            callback(ctx, row_values);
            
            // Clean up text values
            for (uint32_t j = 0; j < table->header->column_count; j++) {
                value_destroy(&row_values[j]);
            }
        }
        
        current_row += table->header->row_size;
    }
    
    free(row_values);
    return true;
}

// Utility functions
const ColumnDesc* table_get_column(Table *table, const char *name) {
    if (!table || !name) return NULL;
    
    for (uint32_t i = 0; i < table->header->column_count; i++) {
        if (strncmp(table->header->columns[i].name, name, MAX_COLUMN_NAME) == 0) {
            return &table->header->columns[i];
        }
    }
    
    return NULL;
}

size_t table_get_row_count(Table *table) {
    return table ? table->header->num_rows : 0;
}

/* END src/table_v2.c */

/* BEGIN src/ristretto_api.c */
/*
** ristretto_api.c - Exported public Table V2 API (ristretto_* prefix).
**
** The library's internal Table V2 engine (src/table_v2.c) exports the
** unprefixed table_* / value_* symbols that the Go binding and the C test
** suites link against. The public embedding header (embed/ristretto.h)
** presents the same engine under the ristretto_* prefix. This file provides
** the thin exported wrappers that forward the prefixed public API to those
** internal symbols, so an application that includes only ristretto.h and links
** libristretto gets a real, link-able Table V2 surface.
**
** Ordering is load-bearing: RISTRETTO_NO_COMPATIBILITY_LAYER must be defined
** BEFORE including ristretto.h, otherwise the header's compatibility macros
** (#define table_create ristretto_table_create, ...) would rewrite the wrapper
** bodies below into infinite self-recursion.
*/
#define RISTRETTO_NO_COMPATIBILITY_LAYER


/*
** The public RistrettoValue / RistrettoColumnDesc / RistrettoTableHeader types
** are layout-identical to the internal Value / ColumnDesc / TableHeader types
** (same field order, same MAX_COLUMN_NAME, same header size). These tripwires
** prove that per build platform; the ColumnDesc assert in particular would
** have caught the historical 8-vs-32 MAX_COLUMN_NAME ABI mismatch at compile
** time.
*/
_Static_assert(sizeof(RistrettoValue) == sizeof(Value),
               "RistrettoValue / Value ABI mismatch");
_Static_assert(sizeof(RistrettoColumnDesc) == sizeof(ColumnDesc),
               "RistrettoColumnDesc / ColumnDesc ABI mismatch");
_Static_assert(sizeof(RistrettoTableHeader) == sizeof(TableHeader),
               "RistrettoTableHeader / TableHeader ABI mismatch");

/* C treats RistrettoValue and Value as distinct types even though they share a
** layout, so a by-value Value cannot be returned directly as a RistrettoValue.
** Convert explicitly through a byte copy. */
static RistrettoValue rv_from_value(Value v) {
    RistrettoValue r;
    memcpy(&r, &v, sizeof r);
    return r;
}

/* ---- Table lifecycle ----------------------------------------------------- */
RistrettoTable* ristretto_table_create(const char *name, const char *schema_sql) {
    return (RistrettoTable*)table_create(name, schema_sql);
}

RistrettoTable* ristretto_table_open(const char *name) {
    return (RistrettoTable*)table_open(name);
}

RistrettoTable* ristretto_table_create_ex(const char *name, const char *schema_sql,
                                          const char *base_dir, int open_mode) {
    return (RistrettoTable*)table_create_ex(name, schema_sql, base_dir, open_mode);
}

RistrettoTable* ristretto_table_open_ex(const char *name, const char *base_dir) {
    return (RistrettoTable*)table_open_ex(name, base_dir);
}

void ristretto_table_close(RistrettoTable *table) {
    table_close((Table*)table);
}

/* ---- Core operations ----------------------------------------------------- */
bool ristretto_table_append_row(RistrettoTable *table, const RistrettoValue *values) {
    return table_append_row((Table*)table, (const Value*)values);
}

bool ristretto_table_append_row_n(RistrettoTable *table, const RistrettoValue *values,
                                  uint32_t value_count) {
    return table_append_row_n((Table*)table, (const Value*)values, value_count);
}

bool ristretto_table_select(RistrettoTable *table,
                            void (*callback)(void *ctx, const RistrettoValue *row),
                            void *ctx) {
    /* RistrettoValue and Value are layout-identical, so the callback pointer
    ** types differ only in the row parameter's (compatible) type. */
    void (*cb)(void *, const Value *) = (void (*)(void *, const Value *))callback;
    return table_select((Table*)table, cb, ctx);
}

/* ---- File management ----------------------------------------------------- */
bool ristretto_table_flush(RistrettoTable *table) {
    return table_flush((Table*)table);
}

bool ristretto_table_flush_durable(RistrettoTable *table) {
    return table_flush_durable((Table*)table);
}

bool ristretto_table_remap(RistrettoTable *table) {
    return table_remap((Table*)table);
}

bool ristretto_table_ensure_space(RistrettoTable *table, size_t needed_bytes) {
    return table_ensure_space((Table*)table, needed_bytes);
}

/* ---- Schema and metadata ------------------------------------------------- */
bool ristretto_table_parse_schema(const char *schema_sql, RistrettoColumnDesc *columns,
                                  uint32_t *column_count, uint32_t *row_size) {
    return table_parse_schema(schema_sql, (ColumnDesc*)columns, column_count, row_size);
}

const RistrettoColumnDesc* ristretto_table_get_column(RistrettoTable *table, const char *name) {
    return (const RistrettoColumnDesc*)table_get_column((Table*)table, name);
}

size_t ristretto_table_get_row_count(RistrettoTable *table) {
    return table_get_row_count((Table*)table);
}

/* ---- Row packing/unpacking ----------------------------------------------- */
bool ristretto_table_pack_row(RistrettoTable *table, const RistrettoValue *values,
                              uint8_t *row_buffer) {
    return table_pack_row((Table*)table, (const Value*)values, row_buffer);
}

bool ristretto_table_unpack_row(RistrettoTable *table, const uint8_t *row_buffer,
                                RistrettoValue *values) {
    return table_unpack_row((Table*)table, row_buffer, (Value*)values);
}

/* ---- Value utilities ----------------------------------------------------- */
RistrettoValue ristretto_value_integer(int64_t val) { return rv_from_value(value_integer(val)); }
RistrettoValue ristretto_value_real(double val)     { return rv_from_value(value_real(val)); }
RistrettoValue ristretto_value_text(const char *str){ return rv_from_value(value_text(str)); }
RistrettoValue ristretto_value_null(void)           { return rv_from_value(value_null()); }

void ristretto_value_destroy(RistrettoValue *value) {
    value_destroy((Value*)value);
}

/* ---- Utility functions --------------------------------------------------- */
uint64_t ristretto_get_time_ms(void)         { return get_time_ms(); }
bool     ristretto_create_data_directory(void) { return create_data_directory(); }

/* END src/ristretto_api.c */
